# Generated by Django 2.1.5 on 2019-01-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyscheduletransaction',
            name='order_qty',
        ),
        migrations.AlterField(
            model_name='supplyscheduletransaction',
            name='delivery_order',
            field=models.ForeignKey(help_text='The delivery order linked to this receipt confirmation.', on_delete=django.db.models.deletion.CASCADE, to='fuel.DeliveryOrder', verbose_name='Delivery Order No.'),
        ),
        migrations.AlterField(
            model_name='supplyscheduletransaction',
            name='eta',
            field=models.DateField(help_text='The Estimated Time of Arrival of the order that is being made.', verbose_name='Estimated Arrival Date'),
        ),
        migrations.AlterField(
            model_name='supplyscheduletransaction',
            name='transaction_no',
            field=models.AutoField(default=0, help_text='The id number for the supply transaction', primary_key=True, serialize=False, verbose_name='Transaction number'),
        ),
    ]
